INTENT_MATCH_INSIGHT="match-insight"
INTENT_BET_ADVICE="bet-advice"
INTENT_STOCK_PREDICT="stock-predict"
INTENT_SMART_ALERT="smart-alert"
INTENT_CHAT="chat"

ALL_INTENTS=[
    INTENT_MATCH_INSIGHT,
    INTENT_BET_ADVICE,
    INTENT_STOCK_PREDICT,
    INTENT_SMART_ALERT,
    INTENT_CHAT
]

COLL_MATCH="Match"
COLL_TEAM="Team"
COLL_PLAYER="Player"
COLL_STOCK="Stock"
COLL_STOCK_TRANSACTION="StockTransaction"
COLL_STOCKHOLDER="Stockholder"
COLL_BET="Bet"
COLL_MATCHBET="Matchbet"
COLL_MATCHBET_OUTCOMES="Matchbetoutcomes"
COLL_ODDS_HISTORY="OddsHistory"
COLL_PRICE_HISTORY="PriceHistory"

COLL_ALERT="Alert"
COLL_NOTIFICATION="Notification"
COLL_WALLET="Wallet"
COLL_USER="User"
COLL_AI_INSIGHT="AIInsight"
COLL_CHAT_MESSAGE="ChatMessage"
COLL_SCRAPED_DOC="ScrapedDocument"
COLL_AGENT_CHECKPOINT="AgentCheckpoint"
QDRANT_COLLECTION="aiengine_cohere"
