version: '3.8'

services:
  app:
    container_name: bettingengine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      ARCJET_ENV: production
    restart: unless-stopped